"""initial migration

Revision ID: 83941195d793
Revises: 
Create Date: 2025-08-09 16:39:25.298243

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83941195d793'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ticket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('po_ticket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('center', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('model', sa.Enum('Notebook', 'MFF', 'AllInOne', 'Backpack', 'DockingStation', 'Monitor', name='modelenum'), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'RESERVED', 'IMAGING', 'SHIPPED', 'COMPLETED', name='statusenum'), nullable=False),
    sa.Column('enduser', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('admin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('missing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_id'), 'hardware', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hardware_id'), table_name='hardware')
    op.drop_table('hardware')
    # ### end Alembic commands ###
