services:
  db:
    image: postgres:17.5
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "9030:8080"
    depends_on:
      - db

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ../app:/app/app
      - ../static:/app/static
      - ../scripts:/app/scripts

volumes:
  db_data:
