services:
  db:
    image: postgres:17.5
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "9030:8080"
    depends_on:
      - db

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9060:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-false}
      APP_HOST: ${APP_HOST:-0.0.0.0}
      APP_PORT: ${APP_PORT:-8000}
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ../app:/app/app
      - ../static:/app/static
      - ../scripts:/app/scripts

volumes:
  db_data:
